apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - image: fatmaguidara/api
        imagePullPolicy: Always
        name: api

        env:
        - name: API-PORT
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: port
              
        ports:
        - containerPort: 5000