apiVersion: v1
kind: Service
metadata:
  name: api-service
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: ecommerce
spec:
  type: LoadBalancer
  selector:
      app: api
  ports:
  - name: express-port
    protocol: TCP
    port: 5000
    targetPort: 5000